name: Release
run-name: Release ${{ github.event.inputs.package }} ${{ github.event.inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
      package:
        type: choice
        description: 'Package to publish'
        required: true
        default: '@cdklib/config'
        options:
          - '@cdklib/config'
          - '@cdklib/argo-synth'
          - '@cdklib/aws-policy'
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Set up Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Version and Publish ${{ github.event.inputs.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm run --filter ${{ github.event.inputs.package }} version ${{ github.event.inputs.version }} -m "chore(release): ${{ github.event.inputs.package }} %s"
          pnpm run --filter ${{ github.event.inputs.package }} publish

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: '${{ github.event.inputs.package }} ${{ github.event.inputs.version }}'
          tag_name: '${{ github.event.inputs.package }}@${{ github.event.inputs.version }}'
